config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"

  get "/dashboard", to: "users#show", as: "dashboard"

  resources :leagues, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/league.rb
class League < ApplicationRecord
  resourcify

  validates :name, presence: true, uniqueness: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class NotAuthorizedError < StandardError
  end

  rescue_from NotAuthorizedError do |exception|
    redirect_to dashboard_path, alert: "You are not authorized to access this page."
  end

  def user_is_member_or_better?(user, league)
    user.has_role?(:member, league) || user.has_role?(:owner, league)
  end

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_path
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    if @league.save && current_user.add_role(:owner, @league)
      redirect_to league_path(@league)
    else
      render :new
    end
  end

  def show
    @league = League.find(params[:id])
    raise NotAuthorizedError unless user_is_member_or_better?(current_user, @league)
  end

  private

  def league_params
    params.require(:league).permit(:name, :description, :location, :public_league)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leagues Replacement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/leagues/new.html.erb
<%= form_with(model: @league, url: leagues_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :public_league %>
    <%= form.check_box :public_league %>
  </div>

  <div class="actions">
    <%= form.submit "Create League" %>
  </div>
<% end %>

app/views/leagues/show.html.erb
<h1><%= @league.name %></h1>
<p><%= @league.description %></p>
<p>Location: <%= @league.location %></p>
<p>Public League: <%= @league.public_league ? 'Yes' : 'No' %></p>

app/views/pages/index.html.erb
<h1>Leagues</h1>

app/views/shared/_navbar.html.erb
<nav>
  <% if current_user %>
    <% unless current_page?(dashboard_path) %>
      <%= link_to "Dashboard", dashboard_path %>
    <% end %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
</nav>

app/views/users/show.html.erb
<h1>Dashboard</h1>
<h2><%= current_user.email %></h2>